# Generated by Django 5.0 on 2026-09-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_created_at_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'طالب'), ('course_manger', 'مدير الدورات')], max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
