# Generated by Django 5.0 on 2026-09-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'طالب'), ('courses_manager', 'مدير الدورات')], max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
