# Generated by Django 6.1.1 on 2026-09-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_enrollment_status_alter_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='courses/', verbose_name='صورة الدورة'),
        ),
    ]
